feat: Filter Pushdown Rule
cmu-db/optd-original pull request #140
Opened 2024-03-26 23:21 UTC by jurplel

This PR brings a filter pushdown heuristic rule, built on @AveryQi115's hybrid scheme.

### Filter Pushdown Rule
- The rule matches on any filter node, and will recursively traverse the entire tree, pushing the filter down as far as possible.
- Each transpose operation is a separate function, so the rule could be modified to be a series of rules instead of a single rule in the future, if desired.

### Helper Functions
- `LogOpExpr::new_flattened_nested_logical` creates a new `LogOpExpr` from an `ExprList`, and it flattens any nested `LogOpExpr`s of the same `LogOpType`.
- `Expr::rewrite_column_refs` recursively rewrites any `ColumnExpr` in an expression tree, using a provided `rewrite_fn`.
- `LogicalJoin::map_through_join` takes in left/right schema sizes, and maps an index to be as it would if it were pushed down to the left or right side of a join.
- `LogicalProjection::compute_column_mapping` creates a `ColumnMapping` object from a `LogicalProjection`. 
    - The `ColumnMapping` object has a few methods, but most importantly it has `rewrite_condition`, which given an expr, will rewrite the expression with the projection's mapping.

### Testing Utilities
- `new_test_optimizer` creates a new heuristic optimizer, which applies a given rule. It uses a `TpchCatalog`.
- `TpchCatalog` is a catalog implementing a couple of tables from the TPC-H schema. It can be extended to have more as needed.
- `DummyCostModel` implements a cost model, only giving zero cost. It is used for constructing a cascades optimizer without a real cost model, and isn't used in this PR.

2024-03-27 20:57 UTC, yliang412 commented
I was looking at Umbra's plan For Q7. Would it be helpful to push down hints for the `(n1.n_name = 'FRANCE' AND n2.n_name = 'GERMANY')
                OR (n1.n_name = 'GERMANY' AND n2.n_name = 'FRANCE')` predicate? You still need to keep the join, but you could push down `FRANCE` or `GERMANY` to both sides and reduce the number of things to look at.



TPC-H Q7:
```sql
SELECT
    supp_nation,
    cust_nation,
    l_year,
    SUM(volume) AS revenue
FROM
    (
        SELECT
            n1.n_name AS supp_nation,
            n2.n_name AS cust_nation,
            EXTRACT(YEAR FROM l_shipdate) AS l_year,
            l_extendedprice * (1 - l_discount) AS volume
        FROM
            supplier,
            lineitem,
            orders,
            customer,
            nation n1,
            nation n2
        WHERE
            s_suppkey = l_suppkey
            AND o_orderkey = l_orderkey
            AND c_custkey = o_custkey
            AND s_nationkey = n1.n_nationkey
            AND c_nationkey = n2.n_nationkey
            AND (
                (n1.n_name = 'FRANCE' AND n2.n_name = 'GERMANY')
                OR (n1.n_name = 'GERMANY' AND n2.n_name = 'FRANCE')
            )
            AND l_shipdate BETWEEN DATE '1995-01-01' AND DATE '1996-12-31'
    ) AS shipping
GROUP BY
    supp_nation,
    cust_nation,
    l_year
ORDER BY
    supp_nation,
    cust_nation,
    l_year;
```

2024-03-27 21:17 UTC, jurplel commented
> I was looking at Umbra's plan For Q7. Would it be helpful to push down hints for the `(n1.n_name = 'FRANCE' AND n2.n_name = 'GERMANY') OR (n1.n_name = 'GERMANY' AND n2.n_name = 'FRANCE')` predicate? You still need to keep the join, but you could push down `FRANCE` or `GERMANY` to both sides and reduce the number of things to look at.
> ...

This is a great example, but if you look at what Umbra is doing, this is actually a separate step from pushdown:
**Unoptimized:**
<img width="361" alt="image" src="https://github.com/cmu-db/optd/assets/10716694/d15a6c6c-b958-46ca-a4c3-01493d740028">
**Expression Simplification:**
<img width="714" alt="image" src="https://github.com/cmu-db/optd/assets/10716694/9f8a533a-cf2c-4e4e-b5cb-4cda127f3c3a">

If the filter were simplified to a conjunction first, then the filter pushdown implementation would be able to operate on it. Dealing with an `in` expression with two columns is a separate issue, but I'm not sure optd would simplify the expression like that.

2024-03-27 22:23 UTC, yliang412 commented
> > I was looking at Umbra's plan For Q7. Would it be helpful to push down hints for the `(n1.n_name = 'FRANCE' AND n2.n_name = 'GERMANY') OR (n1.n_name = 'GERMANY' AND n2.n_name = 'FRANCE')` predicate? You still need to keep the join, but you could push down `FRANCE` or `GERMANY` to both sides and reduce the number of things to look at.
> > ...
> 
> This is a great example, but if you look at what Umbra is doing, this is actually a separate step from pushdown: **Unoptimized:** <img alt="image" width="361" src="https://private-user-images.githubusercontent.com/10716694/317519209-d15a6c6c-b958-46ca-a4c3-01493d740028.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NzgzNDAsIm5iZiI6MTcxMTU3ODA0MCwicGF0aCI6Ii8xMDcxNjY5NC8zMTc1MTkyMDktZDE1YTZjNmMtYjk1OC00NmNhLWE0YzMtMDE0OTNkNzQwMDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDIyMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiY2QxMjUzNjE4ZDEwNzA3ZTlkYzBmZmVhNmYzYWE1MDhlOWFjZWQ1Zjk1NjY0NzQyZmIxNDUxZDkwMmM3NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Hm7jyCepDD2sx4VFtZZh0If3TPm3eTNnLhOkCnbKkA"> **Expression Simplification:** <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/10716694/317519306-9f8a533a-cf2c-4e4e-b5cb-4cda127f3c3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NzgzNDAsIm5iZiI6MTcxMTU3ODA0MCwicGF0aCI6Ii8xMDcxNjY5NC8zMTc1MTkzMDYtOWY4YTUzM2EtY2YyYy00ZTRlLWI1Y2ItNGNkYTEyN2YzYzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDIyMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMDdjNjI4MDZkZjY3Mzg5OTc2MzA1NGFjZTUyNDdiNThlNzkxMjc5MjNmNGM5MGViZmZlOGU3MzhiMjM2MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GFS6h-882-E4ufAtGHBW39gDp8lxK09jGp1Q6gPIGwk">
> 
> If the filter were simplified to a conjunction first, then the filter pushdown implementation would be able to operate on the clauses independently. Dealing with an `in` expression with two columns is a separate issue, but I'm not sure optd would simplify the expression like that.

Yep, I agree that this seems to be relevant to expression optimizations.

2024-03-29 01:18 UTC, Sweetsuro commented on optd-datafusion-repr/src/lib.rs
> +use crate::rules::{
Will we need more transpose rules after support for left semi join + left anti join are added?

2024-03-29 01:22 UTC, Sweetsuro commented on optd-datafusion-repr/src/plan_nodes/join.rs
> +    /// Takes in left/right schema sizes, and maps an index to be as if it were
What is an index?

2024-03-29 01:23 UTC, Sweetsuro commented on optd-datafusion-repr/src/plan_nodes/join.rs
> +        index: usize,
I guess change variable name + comment to specify column index?

2024-03-29 01:28 UTC, Sweetsuro commented on optd-datafusion-repr/src/plan_nodes/projection.rs
> +    /// node is rewriting. E.g. if Projection is A -> B, B will be rewritten as A
Kind of unclear, maybe putting an example would help?

2024-03-29 01:32 UTC, Sweetsuro commented on optd-datafusion-repr/src/plan_nodes/projection.rs
> +impl ProjectionMapping {
Maybe add a comment here specifying how projection mapping works/its intention?

2024-03-29 02:04 UTC, Sweetsuro commented on optd-datafusion-repr/src/testing.rs
> +    HeuristicsOptimizer::new_with_rules(
Switch to cascades optimizer?

2024-03-29 02:05 UTC, Sweetsuro commented on optd-datafusion-repr/src/testing/dummy_cost.rs
> +use crate::plan_nodes::OptRelNodeTyp;
Is optd still able to select a winner if all costs are the same?

2024-03-29 02:09 UTC, Sweetsuro commented on optd-datafusion-repr/src/rules/filter_pushdown.rs
> +fn determine_join_cond_dep(
Add a comment for what this is used for maybe?

2024-03-29 02:11 UTC, Sweetsuro commented on optd-datafusion-repr/src/rules/filter_pushdown.rs
> +/// We check neither of those things and do it always (which may be wrong)
Add this to some kind of issue list? Along with the missing pull up rules

2024-03-29 02:15 UTC, Sweetsuro commented on optd-datafusion-repr/src/rules/filter_pushdown.rs
> +/// - Push into the join condition (involves keys from both children)
For something like 
filter cond = a.0=1 OR b.1=1 
or filter cond = (a.0=1 AND a.1) OR b.1=1

when there are no ANDs across tables, logically I think you'd still want to push the separated filters pass the join cond

2024-03-29 02:46 UTC, Sweetsuro commented on optd-datafusion-repr/src/rules/filter_pushdown.rs
> +    let new_filter = LogicalFilter::new(
Extra filter node on the outside of agg here. Also can flatten the LogOpExpr

2024-03-29 02:46 UTC, Sweetsuro commented on optd-datafusion-repr/src/rules/filter_pushdown.rs
> +            LogOpExpr::new(LogOpType::And, ExprList::new(push_conds)).into_expr(),
flatten the LogOpExpr

2024-03-29 02:55 UTC, Sweetsuro requested changes
Left a couple comments that should probably be addressed

2024-03-29 23:57 UTC, jurplel commented on optd-datafusion-repr/src/lib.rs
> +use crate::rules::{
Moved the rules. We can add them to some list of potential future rules

2024-03-30 00:13 UTC, jurplel commented on optd-datafusion-repr/src/plan_nodes/projection.rs
> +    /// node is rewriting. E.g. if Projection is A -> B, B will be rewritten as A
There was already an example, but i fleshed it out a bit more. hopefully better.

2024-03-30 01:02 UTC, jurplel commented on optd-datafusion-repr/src/rules/filter_pushdown.rs
> +/// We check neither of those things and do it always (which may be wrong)
This is going to have to come with support for data about the volatility of an expression, which i don't think is on the road map right now. Where should I note this down?

2024-03-30 01:16 UTC, jurplel commented on optd-datafusion-repr/src/testing/dummy_cost.rs
> +use crate::plan_nodes::OptRelNodeTyp;
You're right, and this is blocking switching to cascades I think. It is unable to find a winner when I switch to cascades.

Making a dummy cost model with actual numbers is kinda non-trivial i think

2024-04-04 04:32 UTC, yliang412 approved these changes
Overall LGTM. Feel free to merge after addressing the comments (or do it in a separate PR)

2024-04-04 04:32 UTC, yliang412 commented on optd-datafusion-repr/src/rules/filter_pushdown.rs
> +fn determine_join_cond_dep(
potentially useful for other rules, we can make it pub later.

2024-04-04 04:32 UTC, yliang412 commented on optd-datafusion-repr/src/rules/filter_pushdown.rs
> +/// Do not call directly
Could define the helper nested in the actual function

2024-04-04 04:32 UTC, yliang412 commented on optd-datafusion-repr/src/rules/filter_pushdown.rs
> +/// involves the group by columns.
What are we doing if the filter condition involves the agg columns?

2024-04-04 04:32 UTC, yliang412 commented on optd-datafusion-repr/src/rules/filter_pushdown.rs
> +/// involves the group by columns.
nvm, you only push the filters that can be pushed, the other ones are kept. Could you maybe document this? I feel although everything is called `FilterXXXTransposeRule`, what they actually do are kinda different.

2024-04-09 04:04 UTC, jurplel commented on optd-datafusion-repr/src/testing.rs
> +    HeuristicsOptimizer::new_with_rules(
#152

2024-04-09 04:22 UTC, jurplel commented on optd-datafusion-repr/src/rules/filter_pushdown.rs
> +/// We check neither of those things and do it always (which may be wrong)
noted in #153

2024-04-09 04:59 UTC, jurplel commented
@Sweetsuro all comments finally addressed—approve and i will merge it!

2024-04-09 05:09 UTC, Sweetsuro approved these changes
LGTM! Maybe update the PR description before merging

2024-04-09 15:22 UTC, merged